name: Deploy to next-cron

on: [push]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy-next-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm whoami
      - run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm install @dwayneyuen/next-jobs-cli
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
